[package]
name = "meta-voice-chat-neteq"
version = "0.1.0"
edition = "2024"

[dependencies]
neteq = "0.7.1"

[lib]
crate-type = ["cdylib"]

[target.aarch64-linux-android]
rustflags = ["-C", "link-arg=-Wl,-z,max-page-size=16384"]

[target.x86_64-linux-android]
rustflags = ["-C", "link-arg=-Wl,-z,max-page-size=16384"]